from __future__ import annotations

from ..constants import (  # noqa: F401
    AUDIO_CHANNELS,
    AUDIO_SAMPLE_RATE,
    AUDIO_SAMPLE_WIDTH,
    BYTES_PER_SECOND,
    HALLUCINATION_PATTERNS,
    OPENAI_TTS_DEFAULT_VOICE,
    OPENAI_TTS_VOICES,
    PINYIN_TONE_MARKS,
)
from .filtering import (  # noqa: F401
    AVG_LOGPROB_THRESHOLD,
    NO_SPEECH_PROB_THRESHOLD,
)
from .network import (  # noqa: F401
    MAX_RETRIES,
    RETRY_DELAY_SEC,
    TRANSLATE_TIMEOUT_SEC,
    VOICE_CONNECT_TIMEOUT_SEC,
)
from .openai import (  # noqa: F401
    MAX_PENDING_UTTERANCES,
    OPENAI_CHAT_MAX_INPUT_CHARS,
    OPENAI_MAX_CONCURRENT_REQUESTS,
    OPENAI_MAX_REQUESTS_PER_SEC,
    OPENAI_SENTENCE_TIMEOUT_SEC,
    OPENAI_STT_TIMEOUT_SEC,
    OPENAI_TRANSLATION_MODEL,
    OPENAI_TTS_MAX_INPUT_CHARS,
    OPENAI_TTS_MODEL,
    OPENAI_TTS_TIMEOUT_SEC,
    OPENAI_WHISPER_MAX_AUDIO_BYTES,
    SENTENCE_COMPLETION_MODEL,
    USE_AI_SENTENCE_DETECTION,
    WHISPER_PROMPT,
)
from .playback import (  # noqa: F401
    PLAYBACK_SILENCE_MAX_WAIT_SEC,
    TTS_VOLUME,
)
from .providers import (  # noqa: F401
    DEEPL_MAX_REQUEST_BYTES,
    DEEPL_MAX_REQUESTS_PER_SEC,
    DEEPL_USAGE_LOG_EVERY_SEC,
    DEEPL_USAGE_WARN_PERCENT,
    GOOGLE_MAX_INPUT_CHARS,
    GOOGLE_MAX_REQUESTS_PER_SEC,
)
from .vad import (  # noqa: F401
    MAX_UTTERANCE_SEC,
    MIN_SPEECH_RMS,
    MIN_UTTERANCE_SEC,
    NOISE_FLOOR_ALPHA,
    PACKET_TIMEOUT_SEC,
    RMS_SILENCE_THRESHOLD,
    SILENCE_DURATION_SEC,
    SPEECH_CONFIRMATION_SEC,
    SPEECH_THRESHOLD_MULTIPLIER,
)
